name: GitHub Action pytest

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Pip Install
        run: |
          set -v
          set -e
          python -m pip install --upgrade pip
          pip install -q -e .[tensorflow,jax,models,tests]
      - name: Test Import
        run: |
          set -v
          set -e
          python -c "import uncertainty_baselines as ub"
          python -c "import uncertainty_baselines as ub; print(ub.datasets)"
          python -c "import uncertainty_baselines as ub; print(ub.models)"
      - name: Run Pytest
        run: |
          set -v
          set -e
          python -m unittest -v baselines/jft/*_test.py
          python -m unittest -v uncertainty_baselines/datasets/random_test.py
          python -m unittest -v uncertainty_baselines/models/*_test.py
          python -m unittest -v uncertainty_baselines/*_test.py
